vim.wo.number = true -- 默认显示行号(默认: false) Make line numbers default (default: false)
vim.o.relativenumber = true -- 设置相对行号 (默认: false) Set relative numbered lines (default: false)
vim.o.clipboard = 'unnamedplus' -- 在操作系统和Neovim之间同步粘贴板 Sync clipboard between OS and Neovim. (default: '')
vim.o.wrap = false -- 将行显示为一条长行 Display lines as one long line (default: true)
vim.o.linebreak = true -- 与wrap配合使用，不分割单词 Companion to wrap, don't split words (default: false)
vim.o.mouse = 'a' -- 启动鼠标模式 Enable mouse mode (default: '')
vim.o.autoindent = true -- 在开始新行时复制当前行的缩进 Copy indent from current line when starting new one (default: true)
vim.o.ignorecase = true -- 忽略大小写搜索，除非搜索中包含\C或大写字母 Case-insensitive searching UNLESS \C or capital in search (default: false)
vim.o.smartcase = true -- 智能大小写 Smart case (default: false)
vim.o.shiftwidth = 4 -- 每次缩进插入的空格数 The number of spaces inserted for each indentation (default: 8)
vim.o.tabstop = 4 -- 制表符转换为n个空格 Insert n spaces for a tab (default: 8)
vim.o.softtabstop = 4 --  Number of spaces that a tab counts for while performing editing operations (default: 0)
vim.o.expandtab = true -- 将制表符转换为空格 Convert tabs to spaces (default: false)
vim.o.scrolloff = 4 -- 光标上方和下方保持的最小屏幕行数 Minimal number of screen lines to keep above and below the cursor (default: 0)
vim.o.sidescrolloff = 8 -- 如果wrap为false, 光标两次保持的最小屏幕列数 Minimal number of screen columns either side of cursor if wrap is `false` (default: 0)
vim.o.cursorline = false -- 高亮显示当前行 Highlight the current line (default: false)
vim.o.splitbelow = true -- 强制所有水平分割窗口位于当前窗口下方 Force all horizontal splits to go below current window (default: false)
vim.o.splitright = true -- 强制所有垂直分割窗口位于当前窗口右侧 Force all vertical splits to go to the right of current window (default: false)
vim.o.hlsearch = false -- 设置搜索时高亮显示 Set highlight on search (default: true)
vim.o.showmode = false -- 不需要看到类似 INSERT 模式信息 We don't need to see things like -- INSERT -- anymore (default: true)
vim.opt.termguicolors = true -- 设置 termguicolors 弃用高亮组 Set termguicolors to enable highlight groups (default: false)
vim.o.whichwrap = 'bs<>[]hl' -- Which "horizontal" keys are allowed to travel to prev/next line (default: 'b,s')
vim.o.numberwidth = 4 -- Set number column width to 2 {default 4} (default: 4)
vim.o.swapfile = false -- Creates a swapfile (default: true)
vim.o.smartindent = true -- Make indenting smarter again (default: false)
vim.o.showtabline = 2 -- Always show tabs (default: 1)
vim.o.backspace = 'indent,eol,start' -- Allow backspace on (default: 'indent,eol,start')
vim.o.pumheight = 10 -- Pop up menu height (default: 0)
vim.o.conceallevel = 0 -- So that `` is visible in markdown files (default: 1)
vim.wo.signcolumn = 'yes' -- Keep signcolumn on by default (default: 'auto')
vim.o.fileencoding = 'utf-8' -- The encoding written to a file (default: 'utf-8')
vim.o.cmdheight = 1 -- More space in the Neovim command line for displaying messages (default: 1)
vim.o.breakindent = true -- Enable break indent (default: false)
vim.o.updatetime = 250 -- Decrease update time (default: 4000)
vim.o.timeoutlen = 300 -- Time to wait for a mapped sequence to complete (in milliseconds) (default: 1000)
vim.o.backup = false -- Creates a backup file (default: false)
vim.o.writebackup = false -- If a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited (default: true)
vim.o.undofile = true -- Save undo history (default: false)
vim.o.completeopt = 'menuone,noselect' -- Set completeopt to have a better completion experience (default: 'menu,preview')
vim.opt.shortmess:append 'c' -- Don't give |ins-completion-menu| messages (default: does not include 'c')
vim.opt.iskeyword:append '-' -- Hyphenated words recognized by searches (default: does not include '-')
vim.opt.formatoptions:remove { 'c', 'r', 'o' } -- Don't insert the current comment leader automatically for auto-wrapping comments using 'textwidth', hitting <Enter> in insert mode, or hitting 'o' or 'O' in normal mode. (default: 'croql')
vim.opt.runtimepath:remove '/usr/share/vim/vimfiles' -- Separate Vim plugins from Neovim in case Vim still in use (default: includes this path if Vim is installed)
vim.opt.laststatus = 3
